name: Deploy to github pages
on:
  push:
    branches:
      - master
jobs:
  gh-pages-deploy:
    name: Deploying to gh-pages
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js for use with actions
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1.1.0
        with:
          version: 12.x
      - run: npm ci
        env:
          NODE_AUTH_TOKEN: ${{ secrets.YARN_TOKEN }}
      - run: gh-pages -d build
