name: Deploy to github pages
on:
  push:
    branches:
      - master
jobs:
  gh-pages-deploy:
    name: Deploying to gh-pages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js for use with actions
        uses: actions/setup-node@*
        with:
          version: 12.x
      - run: |
          npm ci
          gh-pages -d build
        env:
          NODE_AUTH_TOKEN: ${{ secrets.YARN_TOKEN }}
